### ISSUE TITLE
how we can send sbyte[] in .net core socket? can you create example for send data by socket?

### ISSUE THREAD

**Issue by myabdolmaleki** [Tochemey/NetCore8583#16]

**Comment by Tochemey** [comment]
@myabdolmaleki there is an util in the code that help you move from sbyte to byte and vice-versa. Here it  https://github.com/Tochemey/NetCore8583/blob/master/NetCore8583/Util/ByteUtil.cs

**Comment by Tochemey** [comment]
Closing this issue since I have not seen any update. Feel free to reopen it.However this is not an issue.
